### ISSUE TITLE
[Question/Suggestion] Regarding forward compatibility

### ISSUE THREAD

**Issue by sj-dan** [RaphiMC/ViaProxy#11]
How plausible would it be, if at all, to allow **clients** as old as beta to join **servers** as new as 1.19.3?

**Comment by RaphiMC** [comment]
It would be possible, but the effort required to allow beta clients to join 1.19 servers is enormous (And not many would use that). Thats why I won't be adding support for clients lower than 1.7.2

**Comment by Outfit8TSB** [comment]
if the support for 1.7.2< happened, protocolsupport users will start to use viaproxy instead... people will have to not worry about 1.4.6-1.6.4 joining without protocolsupportbungee on velocity.
