### ISSUE TITLE
The client doesn't respect MOTD rules

### ISSUE THREAD

**Issue by forkiesassds** [RaphiMC/ViaProxy#19]
Classic servers can use MOTD rules like -hax to disable hacking on servers, however ViaProxy doesn't take this into account

**Comment by RaphiMC** [comment]
Please provide more details on how I can test/replicate that

**Comment by RaphiMC** [comment]
Is this documented anywhere? Where did you get this information?

**Comment by forkiesassds** [comment]
> Is this documented anywhere? Where did you get this information?

https://www.classicube.net/server/host/

**Comment by RaphiMC** [comment]
Fixed it. Release will be pushed when 23w08a releases
