### ISSUE TITLE
Error on startup [NoClassDefFoundError]

### ISSUE THREAD

**Issue by lolsaw** [RaphiMC/ViaProxy#2]
After launching ViaProxy using openjdk "17.0.5 2022-10-18" i get the following error:
![Viaproxy issue](https://user-images.githubusercontent.com/103761687/210872285-604aa74f-46cd-4487-a224-9809d51631d5.PNG)
here is the log since the pop up is too big for my current resolution, and i think it would be useful.
[latest.log](https://github.com/RaphiMC/ViaProxy/files/10355419/latest.log)
Thanks in advance!

**Comment by RaphiMC** [comment]
Fixed in ViaProxy v3.0.1
