### ISSUE TITLE
Error When closing Chest

### ISSUE THREAD

**Issue by lecatos** [RaphiMC/ViaProxy#40]
I was running bedrock (1.19.50) -> Geyser -> Viaproxy -> Java Vanilla server (1.19).

When I open and close any chest, an error occurs and shown in the dump below while the Error message shown on geyser was: StringIndexOutOfBoundsException: offset 1, count 1, length 1

ViaProxy Dump: https://pastebin.com/2iLXMwrg![image](https://user-images.githubusercontent.com/42514615/233796465-8827dfb6-3357-4c2e-8ecb-f6446bdf335a.png)

**Comment by RaphiMC** [comment]
Fixed in ViaProxy 3.0.18. Download the dev version here: https://build.lenni0451.net/job/ViaProxy/184/artifact/build/libs/ViaProxy-3.0.18.jar
