### ISSUE TITLE
optimization?

### ISSUE THREAD

**Issue by KweezyCode** [RaphiMC/ViaProxy#51]
![image](https://github.com/RaphiMC/ViaProxy/assets/36813920/bd598513-b0d1-4700-b1c9-e58fdb7c9f2f)

DMV works much better in that way

UPD: ViaProxy loads my PC more than minecraft 1.19.4 lol

**Comment by RaphiMC** [comment]
Are you sure this is the ViaProxy process (How did you find that out)? How many cores does your system have? How did you get that high CPU usage? I need more information.

**Comment by KweezyCode** [comment]
![image](https://github.com/RaphiMC/ViaProxy/assets/36813920/14679990-6dd8-417b-8a99-62f377a5cec5)

**Comment by RaphiMC** [comment]
That only answers one of the questions. Provide more details of your pc specs and how to reproduce that

**Comment by KweezyCode** [comment]
i leave it running on Intel Pentium J5040

**Comment by RaphiMC** [comment]
And what client version to what server version are you translating to?

**Comment by KweezyCode** [comment]
1.5.2, not even using it, just running in background

**Comment by RaphiMC** [comment]
If its just running in the background thats a bug for sure then. To diagnose that I need you to do some debugging on your end. I am not sure how familiar you are with Java and Java profiling, but I recommend you download the VisualVM profiler on that computer (https://visualvm.github.io/download.html) and run a CPU profiler:

You do that by starting it, selecting ViaProxy in the list and then press "Sampler"
![image](https://github.com/RaphiMC/ViaProxy/assets/50594595/a1dde45b-2f14-4954-a2df-95f61951a853)
In that window click the "CPU" button and let it run for roughly 30 seconds before pressing "Stop".
After that you press the Snapshot button:
![image](https://github.com/RaphiMC/ViaProxy/assets/50594595/3af3ec30-0214-492f-a755-9d7232371a27)
and in that snapshot click the save button:
![image](https://github.com/RaphiMC/ViaProxy/assets/50594595/8049f26e-ecf1-4acf-bb09-3c23f210e441)
Upload the saved snapshot here

**Comment by Gaming32** [comment]
I have also noticed this with ViaProxy in the background.

**Comment by KweezyCode** [comment]
https://tmpfiles.org/1439321/unnamed.nps

**Comment by RaphiMC** [comment]
Are you sure that is the ViaProxy process that is taking up all the CPU? I don't see much anything taking up CPU time. If you have multiple ViaProxies make sure to pick the one using all the CPU time and not a newly started one

**Comment by KweezyCode** [comment]
i am running one ViaProxy instance

**Comment by RaphiMC** [comment]
Well the collected data shows its not doing anything in the background

**Comment by KweezyCode** [comment]
i can record video for you if you don't believe me :P

**Comment by RaphiMC** [comment]
I believe you, but I can't do much if there is no data. Just to be sure you can record a video yes

**Comment by KweezyCode** [comment]
https://tmpfiles.org/1439332/2023-05-2201-06-59.mkv

issue exists even in oracle JRE, so don't look at temurin

**Comment by RaphiMC** [comment]
This is very weird and not normal behaviour. Can you also record to process of creating a performance snapshot file, just to make sure there are no errors there

**Comment by KweezyCode** [comment]
https://tmpfiles.org/1439343/2023-05-2201-18-23.mkv
video of creating dump ^

https://tmpfiles.org/1439344/22052023.nps
dump ^

**Comment by RaphiMC** [comment]
I actually managed to reproduce it from one of the videos where you showed the exact java version. I usually test with Java 17 where this issue does not occurr for me. Only in Java 8 it does. I will look into it when I have time

**Comment by KweezyCode** [comment]
let me test with java 17

**Comment by KweezyCode** [comment]
![image](https://github.com/RaphiMC/ViaProxy/assets/36813920/256739df-d473-493a-bf18-b1f8edad7ea9)

**Comment by RaphiMC** [comment]
So yeah its fixed for you as well in Java 17

**Comment by RaphiMC** [comment]
Fixed it: https://build.lenni0451.net/job/ViaProxy/238/
